# Generated by Django 3.1.1 on 2024-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_scheduledmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
