# Generated by Django 3.1.1 on 2024-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
