# Generated by Django 3.1.1 on 2024-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_user_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channel',
        ),
        migrations.AddField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(related_name='users', to='bot.Channel'),
        ),
    ]
